package:
  name: stacktrace
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1dev0').lstrip('v') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python
    - pip
    - libunwind
  build:
    - {{ compiler('c') }}
  run:
    - python
    - libunwind

test:
  imports:
    - stacktrace
  commands:
    - pytest --pyargs stacktrace -v
  requires:
    - pytest

about:
  home: https://github.com/numba/stacktrace
  license: BSD
  summary: Low-level stacktraces from within Python.
